services:
  - type: web
    name: codegymnasium-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NEXT_PUBLIC_API_URL
        value: https://auth-service-a862.onrender.com
