services:
  - type: web
    name: codegymnasium-frontend
    env: node
    rootDir: frontend
    buildCommand: npm.cmd install && npm.cmd run build
    startCommand: npm.cmd run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
