services:
  - type: web
    name: codegymnasium-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install 
    startCommand: npm run build
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
